name: Build Jupyter Book

on:
  push:
    branches: ["main"]
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  H5PY_SETUP_REQUIRES: 0
  DEB_PYTHON_INSTALL_LAYOUT: deb_system
  LIBGL_ALWAYS_SOFTWARE: 1

jobs:
  build-book:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/lab:stable

    env:
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: html

    steps:
      - uses: actions/checkout@v6

      - name: Install common packages
        uses: ./.github/actions/install-dependencies

      - name: Install Node.js
        run: |
          apt-get update && apt-get install -y nodejs npm

      - name: Install dependencies with conda
        run: |
          conda install -c conda-forge -y fenics-dolfinx jupyter-book meshio h5py seaborn pandas tqdm pyvista sympy
          conda install -c conda-forge -y jupytext nbmake ipyparallel

      - name: Build the book
        run: jupyter-book build .

      - name: Create .nojekyll file
        run: touch ./_build/html/.nojekyll

      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: webpage
          path: ./_build/html
          retention-days: 2
          if-no-files-found: error
