name: Build and Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1" # Weekly build on Mondays at 8 am

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test_stable.yml

  build:
    uses: ./.github/workflows/book_stable.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          name: webpage
          path: ./public

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
