name: Test Notebooks

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]

env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/lab:stable
    env:
      PYVISTA_OFF_SCREEN: true

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/install-dependencies

      - name: Install pip dependencies
        run: |
          python3 -m pip install nbmake jupytext ipyparallel

      - name: Test notebooks
        run: |
          cd notebooks
          pytest --nbmake 
